# Generated by Django 4.1.2 on 2022-10-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(to='recipes.ingredient'),
        ),
    ]
