# Generated by Django 4.1.2 on 2022-10-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_food_type_recipe_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='food_type',
            field=models.CharField(choices=[('Soup', 'Soup'), ('Salad', 'Salad'), ('Appetizer', 'Appetizer'), ('Pasta', 'Pasta'), ('Main Dish', 'Main Dish'), ('Pizza', 'Pizza'), ('Dessert', 'Dessert'), ('Base', 'Base')], default='Base', max_length=9),
            preserve_default=False,
        ),
    ]
