# Generated by Django 4.1.1 on 2022-10-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_slug'),
        ('photos', '0002_rename_photos_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tagged_pet',
            field=models.ManyToManyField(blank=True, to='pets.pet'),
        ),
    ]
