# Generated by Django 4.1.1 on 2022-10-11 18:05

from django.db import migrations, models
import petstagram.photos.vaditarors


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_tagged_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/pet_photos/', validators=[petstagram.photos.vaditarors.validate_file_less_then_5mb]),
        ),
    ]
