# Generated by Django 4.1.1 on 2022-09-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_petphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
