# Generated by Django 4.1 on 2022-09-05 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_expense_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='image',
        ),
    ]
