# Generated by Django 4.1 on 2022-09-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_profile_image_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense_image',
            new_name='image',
        ),
    ]
