# Generated by Django 4.1.2 on 2022-10-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('title', 'price')},
        ),
    ]
